source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'CDTIncrementalStoreTest'

def import_pods
  pod "CDTIncrementalStore", :path => "../"
end

target :ios do
  platform :ios, '7.0'
  link_with 'CDTIS_iOSTests'
  import_pods
end

target :osx do
  platform :osx, '10.8'
  link_with 'CDTIS_OSXTests'
  import_pods
end
